class APIError(Exception):
    """Исключение, вызываемое при неверном ответе API."""
    pass
